#!/bin/sh

mkdir out

npx minify ./src/background.js > ./src/background.min.js
npx minify ./src/content-loader.js > ./src/content-loader.min.js
npx minify ./src/content.js > ./src/content.min.js
npx minify ./popup/popup.js > ./popup/popup.min.js
npx minify ./popup/popup.html > ./popup/popup.min.html

zip -r -FS ./out/discord-youtube-music.xpi \
  ./icons \
  ./popup/vendor \
  ./popup/popup.min.html \
  ./popup/popup.min.js \
  ./src/background.min.js \
  ./src/content-loader.min.js \
  ./src/content.min.js \
  ./manifest.json

rm ./src/background.min.js
rm ./src/content-loader.min.js 
rm ./src/content.min.js
rm ./popup/popup.min.js
rm ./popup/popup.min.html
